/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EingangsrechnungenForm.java
 *
 * Created on 09.06.2011, 00:55:50
 */
package view.dialog;

/**
 *
 * @author Goran-Goggy
 */
public class EingangsrechnungenForm extends javax.swing.JDialog {

    /** Creates new form EingangsrechnungenForm */
    public EingangsrechnungenForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eingangLabel = new javax.swing.JLabel();
        dialogKontaktDatumLabel = new javax.swing.JLabel();
        dialogKontaktPreisLabel = new javax.swing.JLabel();
        dialogEingangPreisLabel = new javax.swing.JTextField();
        dialogEingangScanpfadLabel = new javax.swing.JLabel();
        dialogEingangScanpfadFeld = new javax.swing.JTextField();
        dialogKontaktNameLabel = new javax.swing.JLabel();
        dialogAbbrechen = new javax.swing.JButton();
        dialogEingangHinzufuegen = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        dialogEingangNameCheckbox = new javax.swing.JComboBox();
        dialogEingangDatumFeld = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eingangLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        eingangLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eingangLabel.setText("Eingangsrechnung erstellen");
        eingangLabel.setAlignmentX(0.5F);
        jPanel1.add(eingangLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        dialogKontaktDatumLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dialogKontaktDatumLabel.setText("Datum");
        jPanel1.add(dialogKontaktDatumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        dialogKontaktPreisLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dialogKontaktPreisLabel.setText("Preis");
        jPanel1.add(dialogKontaktPreisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        dialogEingangPreisLabel.setName("Bankinstitut"); // NOI18N
        jPanel1.add(dialogEingangPreisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 150, -1));

        dialogEingangScanpfadLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dialogEingangScanpfadLabel.setText("Scanpfad");
        jPanel1.add(dialogEingangScanpfadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        dialogEingangScanpfadFeld.setName("Strasse"); // NOI18N
        jPanel1.add(dialogEingangScanpfadFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 150, -1));

        dialogKontaktNameLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dialogKontaktNameLabel.setText("Kontakt");
        jPanel1.add(dialogKontaktNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        dialogAbbrechen.setText("Abbrechen");
        dialogAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogAbbrechenActionPerformed(evt);
            }
        });
        jPanel1.add(dialogAbbrechen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, -1));

        dialogEingangHinzufuegen.setText("Rechnung erstellen");
        dialogEingangHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogEingangHinzufuegenActionPerformed(evt);
            }
        });
        jPanel1.add(dialogEingangHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 10));

        dialogEingangNameCheckbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(dialogEingangNameCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, -1));
        jPanel1.add(dialogEingangDatumFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialogAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogAbbrechenActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_dialogAbbrechenActionPerformed

    private void dialogEingangHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogEingangHinzufuegenActionPerformed
}//GEN-LAST:event_dialogEingangHinzufuegenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                EingangsrechnungenForm dialog = new EingangsrechnungenForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dialogAbbrechen;
    private com.toedter.calendar.JDateChooser dialogEingangDatumFeld;
    private javax.swing.JButton dialogEingangHinzufuegen;
    private javax.swing.JComboBox dialogEingangNameCheckbox;
    private javax.swing.JTextField dialogEingangPreisLabel;
    private javax.swing.JTextField dialogEingangScanpfadFeld;
    private javax.swing.JLabel dialogEingangScanpfadLabel;
    private javax.swing.JLabel dialogKontaktDatumLabel;
    private javax.swing.JLabel dialogKontaktNameLabel;
    private javax.swing.JLabel dialogKontaktPreisLabel;
    private javax.swing.JLabel eingangLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
