/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AngebotToKundeForm.java
 *
 * Created on 05.06.2011, 22:22:20
 */
package view.dialog;

import controller.Binder;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Angebot;
import model.Kontakt;
import model.dal.DALException;
import model.dal.DALFactory;
import view.AbstractViewDialog;

/**
 *
 * @author Goran-Goggy
 */
public class KundeToAngebotForm extends AbstractViewDialog {

    private final Angebot angebot;

    /** Creates new form AngebotToKundeForm */
    public KundeToAngebotForm(java.awt.Frame parent, boolean modal, Angebot angebot) {
        super(parent, modal);
        this.angebot = angebot;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        initialize();
    }

    private void initialize() {
        dialogKundeToAngebotNameFeld.setText(angebot.toString());

        Binder.bind(Kontakt.class, dialogKundeToAngebotKundeComboBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        dialogKundeToAngebotKundeLabel = new javax.swing.JLabel();
        dialogKundeToAngebotNameLabel = new javax.swing.JLabel();
        configMenueLabel = new javax.swing.JLabel();
        dialogKundeToAngebotNameFeld = new javax.swing.JTextField();
        dialogKundeToAngebotKundeComboBox = new javax.swing.JComboBox();
        dialogKundeToAngebotAbbrechen = new javax.swing.JButton();
        dialogKundeToAngebotUebernehmen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 10));

        dialogKundeToAngebotKundeLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogKundeToAngebotKundeLabel.setText("Kunde");
        jPanel1.add(dialogKundeToAngebotKundeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        dialogKundeToAngebotNameLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogKundeToAngebotNameLabel.setText("Angebot");
        jPanel1.add(dialogKundeToAngebotNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        configMenueLabel.setFont(new java.awt.Font("Arial", 1, 14));
        configMenueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        configMenueLabel.setText("Angebotzuweisung");
        configMenueLabel.setAlignmentX(0.5F);
        jPanel1.add(configMenueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        dialogKundeToAngebotNameFeld.setEditable(false);
        dialogKundeToAngebotNameFeld.setName("Kunde"); // NOI18N
        jPanel1.add(dialogKundeToAngebotNameFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, -1));

        dialogKundeToAngebotKundeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4", "Item 3", "Item 4" }));
        dialogKundeToAngebotKundeComboBox.setName("KontaktListe"); // NOI18N
        jPanel1.add(dialogKundeToAngebotKundeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, -1));

        dialogKundeToAngebotAbbrechen.setText("Abbrechen");
        dialogKundeToAngebotAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogKundeToAngebotAbbrechenActionPerformed(evt);
            }
        });
        jPanel1.add(dialogKundeToAngebotAbbrechen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, -1));

        dialogKundeToAngebotUebernehmen.setText("Übernehmen");
        dialogKundeToAngebotUebernehmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogKundeToAngebotUebernehmenActionPerformed(evt);
            }
        });
        jPanel1.add(dialogKundeToAngebotUebernehmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialogKundeToAngebotUebernehmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogKundeToAngebotUebernehmenActionPerformed
        Object o = dialogKundeToAngebotKundeComboBox.getSelectedItem();

        if (o != null && o instanceof Kontakt) {
            try {
                DALFactory.getDAL().addAngebotToKontakt((Kontakt) o, angebot);
            } catch (DALException ex) {
                Logger.getLogger(KundeToAngebotForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
}//GEN-LAST:event_dialogKundeToAngebotUebernehmenActionPerformed

    private void dialogKundeToAngebotAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogKundeToAngebotAbbrechenActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_dialogKundeToAngebotAbbrechenActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel configMenueLabel;
    private javax.swing.JButton dialogKundeToAngebotAbbrechen;
    private javax.swing.JComboBox dialogKundeToAngebotKundeComboBox;
    private javax.swing.JLabel dialogKundeToAngebotKundeLabel;
    private javax.swing.JTextField dialogKundeToAngebotNameFeld;
    private javax.swing.JLabel dialogKundeToAngebotNameLabel;
    private javax.swing.JButton dialogKundeToAngebotUebernehmen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
