/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Kontakte.java
 *
 * Created on 09.04.2011, 15:11:42
 */
package gui;

/**
 *
 * @author Goran-Goggy
 */
public class Kontakte extends javax.swing.JPanel {

    /** Creates new form Kontakte */
    public Kontakte() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        kontaktListe = new javax.swing.JList();
        kontaktListeLabel = new javax.swing.JLabel();
        kontaktListeLabel1 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        blzLabel = new javax.swing.JLabel();
        nameFeld = new javax.swing.JTextField();
        bankInstitutFeld = new javax.swing.JTextField();
        BLZFeld = new javax.swing.JTextField();
        kontaktHinzufuegen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        telFeld = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        bankInstitutFeld2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        kontoLabel = new javax.swing.JLabel();
        kontoFeld1 = new javax.swing.JTextField();

        kontaktListe.setFont(new java.awt.Font("Tahoma", 2, 12));
        kontaktListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(kontaktListe);

        kontaktListeLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14));
        kontaktListeLabel.setText("KONTAKTLISTE");

        kontaktListeLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14));
        kontaktListeLabel1.setText("KONTAKTLISTE");

        idLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        idLabel.setText("Name");

        bankLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        bankLabel.setText("Bankname");

        blzLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        blzLabel.setText("BLZ");

        kontaktHinzufuegen.setText("Kontakt hinzufügen");

        jButton1.setText("Angebot zuweisen");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        nameLabel.setText("Telefonnr.");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        emailLabel.setText("Email");

        kontoLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        kontoLabel.setText("Kontonr.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kontaktHinzufuegen, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kontaktListeLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(idLabel)
                                    .addComponent(bankLabel)
                                    .addComponent(blzLabel)
                                    .addComponent(kontoLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BLZFeld)
                                    .addComponent(bankInstitutFeld)
                                    .addComponent(bankInstitutFeld2)
                                    .addComponent(telFeld)
                                    .addComponent(kontoFeld1)
                                    .addComponent(nameFeld, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                            .addComponent(kontaktListeLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kontaktListeLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kontaktListeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nameFeld))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(telFeld))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bankInstitutFeld2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(bankLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bankInstitutFeld))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(blzLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BLZFeld))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(kontoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(kontoFeld1))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kontaktHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kontakte().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BLZFeld;
    private javax.swing.JTextField bankInstitutFeld;
    private javax.swing.JTextField bankInstitutFeld2;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel blzLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kontaktHinzufuegen;
    private javax.swing.JList kontaktListe;
    private javax.swing.JLabel kontaktListeLabel;
    private javax.swing.JLabel kontaktListeLabel1;
    private javax.swing.JTextField kontoFeld1;
    private javax.swing.JLabel kontoLabel;
    private javax.swing.JTextField nameFeld;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField telFeld;
    // End of variables declaration//GEN-END:variables
}
