/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Kunden.java
 *
 * Created on 09.04.2011, 16:39:26
 */

package gui;

/**
 *
 * @author Goran-Goggy
 */
public class Kunden extends javax.swing.JPanel {

    /** Creates new form Kunden */
    public Kunden() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kontaktListeLabel = new javax.swing.JLabel();
        kontaktInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kundenListe = new javax.swing.JList();
        kundenKonto = new javax.swing.JLabel();
        kundenName = new javax.swing.JLabel();
        kundenTel = new javax.swing.JLabel();
        kundenEmail = new javax.swing.JLabel();
        kundenBank = new javax.swing.JLabel();
        kundenBLZ = new javax.swing.JLabel();
        kundenKontoFeld = new javax.swing.JTextField();
        kundenNameFeld = new javax.swing.JTextField();
        kundenTelFeld = new javax.swing.JTextField();
        kundenEmailFeld = new javax.swing.JTextField();
        kundenBankFeld = new javax.swing.JTextField();
        kundenBLZFeld = new javax.swing.JTextField();
        kundenHinzufuegen = new javax.swing.JButton();
        angebotZuweisen = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(572, 380));
        setMinimumSize(new java.awt.Dimension(572, 380));
        setPreferredSize(new java.awt.Dimension(572, 380));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kontaktListeLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        kontaktListeLabel.setText("Kundenliste");
        add(kontaktListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        kontaktInfoLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        kontaktInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kontaktInfoLabel.setLabelFor(kontaktInfoLabel);
        kontaktInfoLabel.setText("Kundeninformation");
        kontaktInfoLabel.setAlignmentX(0.5F);
        add(kontaktInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        kundenListe.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        kundenListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(kundenListe);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 260));

        kundenKonto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        kundenKonto.setText("Kontonr.");
        add(kundenKonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        kundenName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        kundenName.setText("Name");
        add(kundenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        kundenTel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        kundenTel.setText("Telefonnr.");
        add(kundenTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        kundenEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        kundenEmail.setText("Email");
        add(kundenEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        kundenBank.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        kundenBank.setText("Bank");
        add(kundenBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        kundenBLZ.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        kundenBLZ.setText("BLZ-Nr.");
        add(kundenBLZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        add(kundenKontoFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 180, -1));
        add(kundenNameFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 180, -1));
        add(kundenTelFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 180, -1));
        add(kundenEmailFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 180, -1));
        add(kundenBankFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 180, -1));
        add(kundenBLZFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 180, -1));

        kundenHinzufuegen.setText("Kunden hinzufügen/ändern");
        add(kundenHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 260, -1));

        angebotZuweisen.setText("Angebot zuweisen");
        add(angebotZuweisen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton angebotZuweisen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kontaktInfoLabel;
    private javax.swing.JLabel kontaktListeLabel;
    private javax.swing.JLabel kundenBLZ;
    private javax.swing.JTextField kundenBLZFeld;
    private javax.swing.JLabel kundenBank;
    private javax.swing.JTextField kundenBankFeld;
    private javax.swing.JLabel kundenEmail;
    private javax.swing.JTextField kundenEmailFeld;
    private javax.swing.JButton kundenHinzufuegen;
    private javax.swing.JLabel kundenKonto;
    private javax.swing.JTextField kundenKontoFeld;
    private javax.swing.JList kundenListe;
    private javax.swing.JLabel kundenName;
    private javax.swing.JTextField kundenNameFeld;
    private javax.swing.JLabel kundenTel;
    private javax.swing.JTextField kundenTelFeld;
    // End of variables declaration//GEN-END:variables

}
