/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AngebotAddForm.java
 *
 * Created on 14.04.2011, 16:43:58
 */

package Dialog;

/**
 *
 * @author Goran-Goggy
 */
public class AngebotAddForm extends javax.swing.JDialog {

    /** Creates new form AngebotAddForm */
    public AngebotAddForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        angebotAddLabel = new javax.swing.JLabel();
        dialogAngebotAbbrechen = new javax.swing.JButton();
        dialogAngebotHinzufuegen = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        dialogAngebotGueltigBisLabel = new javax.swing.JLabel();
        dialogAngebotNameLabel = new javax.swing.JLabel();
        dialogAngebotPreisLabel = new javax.swing.JLabel();
        dialogAngebotDauerLabel = new javax.swing.JLabel();
        dialogAngebotChanceLabel = new javax.swing.JLabel();
        dialogAngebotPreisFeld = new javax.swing.JTextField();
        dialogAngebotNameFeld = new javax.swing.JTextField();
        dialogAngebotDauerFeld = new javax.swing.JTextField();
        dialogAngebotGueltigBisFeld = new javax.swing.JTextField();
        dialogAngebotBeschreibungLabel = new javax.swing.JLabel();
        dialogAngebotGueltigAbLabel = new javax.swing.JLabel();
        dialogAngebotGueltigAbFeld = new javax.swing.JTextField();
        dialogAngebotChanceFeld = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        dialogAngebotBeschreibungFeld = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        angebotAddLabel.setFont(new java.awt.Font("Arial", 1, 18));
        angebotAddLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        angebotAddLabel.setText("Angebot erstellen");
        angebotAddLabel.setAlignmentX(0.5F);

        dialogAngebotAbbrechen.setText("Abbrechen");
        dialogAngebotAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogAngebotAbbrechenActionPerformed(evt);
            }
        });

        dialogAngebotHinzufuegen.setText("Angebot erstellen");
        dialogAngebotHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogAngebotHinzufuegenActionPerformed(evt);
            }
        });

        dialogAngebotGueltigBisLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogAngebotGueltigBisLabel.setText("Gültig bis");

        dialogAngebotNameLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogAngebotNameLabel.setText("Name");

        dialogAngebotPreisLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogAngebotPreisLabel.setText("Preis");

        dialogAngebotDauerLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogAngebotDauerLabel.setText("Dauer");

        dialogAngebotChanceLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogAngebotChanceLabel.setText("Chance");

        dialogAngebotPreisFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogAngebotPreisFeldActionPerformed(evt);
            }
        });

        dialogAngebotGueltigBisFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogAngebotGueltigBisFeldActionPerformed(evt);
            }
        });

        dialogAngebotBeschreibungLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogAngebotBeschreibungLabel.setText("Beschreibung");

        dialogAngebotGueltigAbLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        dialogAngebotGueltigAbLabel.setText("Gültig ab");

        dialogAngebotGueltigAbFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogAngebotGueltigAbFeldActionPerformed(evt);
            }
        });

        dialogAngebotBeschreibungFeld.setColumns(20);
        dialogAngebotBeschreibungFeld.setRows(5);
        jScrollPane3.setViewportView(dialogAngebotBeschreibungFeld);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addComponent(angebotAddLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dialogAngebotNameLabel)
                                .addGap(41, 41, 41)
                                .addComponent(dialogAngebotNameFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(dialogAngebotGueltigAbLabel)
                                .addGap(24, 24, 24)
                                .addComponent(dialogAngebotGueltigAbFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(dialogAngebotGueltigBisLabel)
                                .addGap(23, 23, 23)
                                .addComponent(dialogAngebotGueltigBisFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dialogAngebotPreisLabel)
                                .addGap(50, 50, 50)
                                .addComponent(dialogAngebotPreisFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(dialogAngebotDauerLabel)
                                .addGap(41, 41, 41)
                                .addComponent(dialogAngebotDauerFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(dialogAngebotChanceLabel)
                                .addGap(32, 32, 32)
                                .addComponent(dialogAngebotChanceFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dialogAngebotBeschreibungLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dialogAngebotHinzufuegen, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dialogAngebotAbbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(angebotAddLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialogAngebotNameLabel)
                    .addComponent(dialogAngebotNameFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialogAngebotGueltigAbLabel)
                    .addComponent(dialogAngebotGueltigAbFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialogAngebotGueltigBisLabel)
                    .addComponent(dialogAngebotGueltigBisFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dialogAngebotPreisLabel)
                    .addComponent(dialogAngebotPreisFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialogAngebotDauerLabel)
                    .addComponent(dialogAngebotDauerFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialogAngebotChanceLabel)
                    .addComponent(dialogAngebotChanceFeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(dialogAngebotBeschreibungLabel)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialogAngebotHinzufuegen)
                    .addComponent(dialogAngebotAbbrechen))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialogAngebotGueltigAbFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogAngebotGueltigAbFeldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dialogAngebotGueltigAbFeldActionPerformed

    private void dialogAngebotGueltigBisFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogAngebotGueltigBisFeldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dialogAngebotGueltigBisFeldActionPerformed

    private void dialogAngebotPreisFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogAngebotPreisFeldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dialogAngebotPreisFeldActionPerformed

    private void dialogAngebotHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogAngebotHinzufuegenActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dialogAngebotHinzufuegenActionPerformed

    private void dialogAngebotAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogAngebotAbbrechenActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_dialogAngebotAbbrechenActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AngebotAddForm dialog = new AngebotAddForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angebotAddLabel;
    private javax.swing.JButton dialogAngebotAbbrechen;
    private javax.swing.JTextArea dialogAngebotBeschreibungFeld;
    private javax.swing.JLabel dialogAngebotBeschreibungLabel;
    private javax.swing.JTextField dialogAngebotChanceFeld;
    private javax.swing.JLabel dialogAngebotChanceLabel;
    private javax.swing.JTextField dialogAngebotDauerFeld;
    private javax.swing.JLabel dialogAngebotDauerLabel;
    private javax.swing.JTextField dialogAngebotGueltigAbFeld;
    private javax.swing.JLabel dialogAngebotGueltigAbLabel;
    private javax.swing.JTextField dialogAngebotGueltigBisFeld;
    private javax.swing.JLabel dialogAngebotGueltigBisLabel;
    private javax.swing.JButton dialogAngebotHinzufuegen;
    private javax.swing.JTextField dialogAngebotNameFeld;
    private javax.swing.JLabel dialogAngebotNameLabel;
    private javax.swing.JTextField dialogAngebotPreisFeld;
    private javax.swing.JLabel dialogAngebotPreisLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
