/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Angebote.java
 *
 * Created on 09.04.2011, 17:52:20
 */
package view;

import controller.AngebotController;
import controller.Binder;
import controller.BinderProperty;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import model.Angebot;
import model.dal.DALException;
import model.dal.DALFactory;
import model.dal.IDAL;
import utils.log.Logger;
import view.dialog.AngebotAddForm;

/**
 *
 * @author Goran-Goggy
 */
public class AngeboteView extends AbstractViewPanel {

    private AngebotController controller;
    private IDAL db = DALFactory.getDAL();

    /** Creates new form Angebote */
    public AngeboteView(AngebotController controller) {
        initComponents();
        this.controller = controller;
        this.initialize();
    }

    private void initialize() {

        Binder.bind(angebotListe, angebotBeschreibungFeld, "Beschreibung");
        Binder.bind(angebotListe, angebotNameFeld, "Name");
        Binder.bind(angebotListe, angebotGueltigAbFeld, "GueltigAb");
        Binder.bind(angebotListe, angebotGueltigBisFeld, "GueltigBis");
        Binder.bind(angebotListe, angebotPreisFeld, "Preis");
        Binder.bind(angebotListe, angebotDauerFeld, "Dauer");
        Binder.bind(angebotListe, angebotChanceFeld, "Chance");


        Binder.bind(Angebot.class, angebotListe);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kontaktListeLabel = new javax.swing.JLabel();
        kontaktInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        angebotListe = new javax.swing.JList();
        angebotGueltigBisLabel = new javax.swing.JLabel();
        kontaktTelLabel = new javax.swing.JLabel();
        kontaktEmailLabel = new javax.swing.JLabel();
        angebotDauerLabel = new javax.swing.JLabel();
        angebotChanceLabel = new javax.swing.JLabel();
        angebotPreisFeld = new javax.swing.JTextField();
        angebotNameFeld = new javax.swing.JTextField();
        angebotDauerFeld = new javax.swing.JTextField();
        angebotErstellen = new javax.swing.JButton();
        angebotLoeschen = new javax.swing.JButton();
        kundeZuweisen = new javax.swing.JButton();
        kontaktStrasseLabel = new javax.swing.JLabel();
        angebotGueltigAbLabel = new javax.swing.JLabel();
        angebotAendern = new javax.swing.JButton();
        angebotChanceFeld = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        angebotBeschreibungFeld = new javax.swing.JTextArea();
        angebotGueltigAbFeld = new com.toedter.calendar.JDateChooser();
        angebotGueltigBisFeld = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setMaximumSize(new java.awt.Dimension(572, 380));
        setMinimumSize(new java.awt.Dimension(572, 380));
        setName("angebotPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(572, 380));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kontaktListeLabel.setFont(new java.awt.Font("Arial", 1, 14));
        kontaktListeLabel.setText("Angebotliste");
        add(kontaktListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        kontaktInfoLabel.setFont(new java.awt.Font("Arial", 1, 14));
        kontaktInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kontaktInfoLabel.setText("Angebotinformation");
        kontaktInfoLabel.setAlignmentX(0.5F);
        add(kontaktInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        angebotListe.setFont(new java.awt.Font("Tahoma", 2, 12));
        angebotListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        angebotListe.setName("AngebotListe"); // NOI18N
        jScrollPane1.setViewportView(angebotListe);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 190));

        angebotGueltigBisLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        angebotGueltigBisLabel.setText("Gültig bis");
        add(angebotGueltigBisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        kontaktTelLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktTelLabel.setText("Name");
        add(kontaktTelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        kontaktEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktEmailLabel.setText("Preis (€)");
        kontaktEmailLabel.setName("Preis"); // NOI18N
        add(kontaktEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        angebotDauerLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        angebotDauerLabel.setText("Dauer (Tage)");
        add(angebotDauerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        angebotChanceLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        angebotChanceLabel.setText("Chance (%)");
        add(angebotChanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, -1));

        angebotPreisFeld.setEnabled(false);
        angebotPreisFeld.setName("Preis"); // NOI18N
        angebotPreisFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angebotPreisFeldActionPerformed(evt);
            }
        });
        add(angebotPreisFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 150, -1));

        angebotNameFeld.setEnabled(false);
        angebotNameFeld.setName("Name"); // NOI18N
        add(angebotNameFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 150, -1));

        angebotDauerFeld.setEnabled(false);
        angebotDauerFeld.setName("Dauer"); // NOI18N
        add(angebotDauerFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 150, -1));

        angebotErstellen.setText("Angebot erstellen");
        angebotErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angebotErstellenActionPerformed(evt);
            }
        });
        add(angebotErstellen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, -1));

        angebotLoeschen.setText("Angebot löschen");
        angebotLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angebotLoeschenActionPerformed(evt);
            }
        });
        add(angebotLoeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 230, -1));

        kundeZuweisen.setText("Kunden zuweisen");
        kundeZuweisen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kundeZuweisenActionPerformed(evt);
            }
        });
        add(kundeZuweisen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        kontaktStrasseLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktStrasseLabel.setText("Beschreibung");
        add(kontaktStrasseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        angebotGueltigAbLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        angebotGueltigAbLabel.setText("Gültig ab");
        add(angebotGueltigAbLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        angebotAendern.setText("Angebot ändern");
        angebotAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angebotAendernActionPerformed(evt);
            }
        });
        add(angebotAendern, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 230, -1));

        angebotChanceFeld.setEnabled(false);
        angebotChanceFeld.setName("Chance"); // NOI18N
        add(angebotChanceFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 140, -1));

        angebotBeschreibungFeld.setColumns(20);
        angebotBeschreibungFeld.setRows(5);
        angebotBeschreibungFeld.setEnabled(false);
        angebotBeschreibungFeld.setName("Beschreibung"); // NOI18N
        jScrollPane3.setViewportView(angebotBeschreibungFeld);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 770, 90));

        angebotGueltigAbFeld.setEnabled(false);
        angebotGueltigAbFeld.setName("GueltigAb"); // NOI18N
        add(angebotGueltigAbFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 140, -1));

        angebotGueltigBisFeld.setEnabled(false);
        angebotGueltigBisFeld.setName("GueltigBis"); // NOI18N
        add(angebotGueltigBisFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void angebotPreisFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angebotPreisFeldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_angebotPreisFeldActionPerformed

    private void angebotErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angebotErstellenActionPerformed
        DefaultListModel model = (DefaultListModel) angebotListe.getModel();
        // solange ein nicht gespeicherter Kontakt, kein neuer Kontakt
        if (((Angebot) model.getElementAt(model.getSize() - 1)).getId() == 0) {
            return;
        }
        Angebot a = new Angebot();
        a.setId(0);
        model.addElement(a);
        angebotListe.setSelectedIndex(model.getSize() - 1);
        this.resetTextFields();
        this.cleanErrors();
        /*
        AngebotAddForm af = new AngebotAddForm(null, true);
        af.setVisible(true);*/
}//GEN-LAST:event_angebotErstellenActionPerformed

    private void angebotAendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angebotAendernActionPerformed
        if (this.angebotListe.isSelectionEmpty()) {
            return;
        }

        ArrayList<String> errorList;
        errorList = Binder.save(Angebot.class, createBinderPropertiesFromFields());
        showErrors(errorList);
        /*
        Date d = new Date();
        Angebot a = new Angebot();
        a.setName(angebotNameFeld.getText());
        a.setAenderungsDatum(d);
        a.setBeschreibung(angebotBeschreibungFeld.getText());
        a.setGueltigAb(angebotGueltigAbFeld.getDate());
        a.setGueltigBis(angebotGueltigBisFeld.getDate());
        a.setChance(Integer.parseInt(angebotChanceFeld.getText()));
        a.setDauer(Integer.parseInt(angebotDauerFeld.getText()));
        a.setPreis(Long.parseLong(angebotPreisFeld.getText()));
        try {
            // Test
            DALFactory.getDAL().saveAngebot(a);
            // --> controller add
            //this.getObservable().notifyObservers(new NotifyObject(k, State.ADDED));
        } catch (DALException ex) {
            Logger.log(Level.SEVERE, AngebotAddForm.class, ex);
        }*/
}//GEN-LAST:event_angebotAendernActionPerformed

    private void kundeZuweisenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kundeZuweisenActionPerformed
        // TODO add your handling code here:
        angebotBeschreibungFeld.setText("klsdajf");
    }//GEN-LAST:event_kundeZuweisenActionPerformed

    private void angebotLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angebotLoeschenActionPerformed
        Angebot a = (Angebot) this.angebotListe.getSelectedValue();
        try {
            if (!(angebotListe.isSelectionEmpty())) {
                db.deleteAngebot(a);
            }
        } catch (DALException ex) {
            Logger.log(Level.SEVERE, KontakteView.class, ex);
        }
    }//GEN-LAST:event_angebotLoeschenActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton angebotAendern;
    private javax.swing.JTextArea angebotBeschreibungFeld;
    private javax.swing.JTextField angebotChanceFeld;
    private javax.swing.JLabel angebotChanceLabel;
    private javax.swing.JTextField angebotDauerFeld;
    private javax.swing.JLabel angebotDauerLabel;
    private javax.swing.JButton angebotErstellen;
    private com.toedter.calendar.JDateChooser angebotGueltigAbFeld;
    private javax.swing.JLabel angebotGueltigAbLabel;
    private com.toedter.calendar.JDateChooser angebotGueltigBisFeld;
    private javax.swing.JLabel angebotGueltigBisLabel;
    private javax.swing.JList angebotListe;
    private javax.swing.JButton angebotLoeschen;
    private javax.swing.JTextField angebotNameFeld;
    private javax.swing.JTextField angebotPreisFeld;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kontaktEmailLabel;
    private javax.swing.JLabel kontaktInfoLabel;
    private javax.swing.JLabel kontaktListeLabel;
    private javax.swing.JLabel kontaktStrasseLabel;
    private javax.swing.JLabel kontaktTelLabel;
    private javax.swing.JButton kundeZuweisen;
    // End of variables declaration//GEN-END:variables

    private void setAngebotListe(ArrayList<Angebot> angebote) {
        DefaultListModel list = new DefaultListModel();
        for (Angebot a : angebote) {
            list.addElement(a);
        }

        this.angebotListe.setModel(list);
    }

    private ArrayList<BinderProperty> createBinderPropertiesFromFields() {
        ArrayList list = new ArrayList<BinderProperty>();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        list.add(new BinderProperty(angebotNameFeld.getName(), angebotNameFeld.getText(), String.class));
        list.add(new BinderProperty("AenderungsDatum", sdf.format(new Date()), Date.class));
        list.add(new BinderProperty(angebotBeschreibungFeld.getName(), angebotBeschreibungFeld.getText(), String.class));
        list.add(new BinderProperty(angebotGueltigAbFeld.getName(), sdf.format(angebotGueltigAbFeld.getDate()), Date.class));
        list.add(new BinderProperty(angebotGueltigBisFeld.getName(), sdf.format(angebotGueltigBisFeld.getDate()), Date.class));
        list.add(new BinderProperty(angebotChanceFeld.getName(), angebotChanceFeld.getText(), Integer.class));
        list.add(new BinderProperty(angebotDauerFeld.getName(), angebotDauerFeld.getText(), Integer.class));
        list.add(new BinderProperty(angebotPreisFeld.getName(), angebotPreisFeld.getText(), Double.class));
        Angebot a = (Angebot) angebotListe.getSelectedValue();
        if(a != null)
            list.add(new BinderProperty("Id", a.getId().toString(), Integer.class));
        else
            list.add(new BinderProperty("Id", "0", Integer.class));

        return list;
    }
}
