/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Kontakte.java
 *
 * Created on 09.04.2011, 15:11:42
 */
package view;

import controller.KontaktController;
import java.beans.PropertyChangeEvent;

/**
 *
 * @author Goran-Goggy
 */
public class Kontakte extends AbstractViewPanel {

    private KontaktController controller;

    /** Creates new form Kontakte */
    public Kontakte(KontaktController controller) {
        this.controller = controller;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kontaktListeLabel = new javax.swing.JLabel();
        kontaktInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kundenListe = new javax.swing.JList();
        kontaktKonto = new javax.swing.JLabel();
        kontaktName = new javax.swing.JLabel();
        kontaktTel = new javax.swing.JLabel();
        kontaktEmail = new javax.swing.JLabel();
        kontaktBank = new javax.swing.JLabel();
        kontaktBLZ = new javax.swing.JLabel();
        kontaktKontoFeld = new javax.swing.JTextField();
        kontaktNameFeld = new javax.swing.JTextField();
        kontaktTelFeld = new javax.swing.JTextField();
        kontaktEmailFeld = new javax.swing.JTextField();
        kontaktBankFeld = new javax.swing.JTextField();
        kontaktBLZFeld = new javax.swing.JTextField();
        kontaktHinzufuegen = new javax.swing.JButton();
        angebotZuweisen = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(572, 380));
        setMinimumSize(new java.awt.Dimension(572, 380));
        setPreferredSize(new java.awt.Dimension(572, 380));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kontaktListeLabel.setFont(new java.awt.Font("Arial", 1, 18));
        kontaktListeLabel.setText("Kontaktliste");
        add(kontaktListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        kontaktInfoLabel.setFont(new java.awt.Font("Arial", 1, 18));
        kontaktInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kontaktInfoLabel.setText("Kontaktinformation");
        kontaktInfoLabel.setAlignmentX(0.5F);
        add(kontaktInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        kundenListe.setFont(new java.awt.Font("Tahoma", 2, 12));
        kundenListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(kundenListe);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 260));

        kontaktKonto.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktKonto.setText("Kontonr.");
        add(kontaktKonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        kontaktName.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktName.setText("Name");
        add(kontaktName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        kontaktTel.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktTel.setText("Telefonnr.");
        add(kontaktTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        kontaktEmail.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktEmail.setText("Email");
        add(kontaktEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        kontaktBank.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktBank.setText("Bank");
        add(kontaktBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        kontaktBLZ.setFont(new java.awt.Font("Tahoma", 0, 15));
        kontaktBLZ.setText("BLZ-Nr.");
        add(kontaktBLZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));
        add(kontaktKontoFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 180, -1));

        kontaktNameFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontaktNameFeldActionPerformed(evt);
            }
        });
        add(kontaktNameFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 180, -1));
        add(kontaktTelFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 180, -1));
        add(kontaktEmailFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 180, -1));
        add(kontaktBankFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 180, -1));
        add(kontaktBLZFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 180, -1));

        kontaktHinzufuegen.setText("Kunden hinzufügen/ändern");
        add(kontaktHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 260, -1));

        angebotZuweisen.setText("Angebot zuweisen");
        add(angebotZuweisen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void kontaktNameFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontaktNameFeldActionPerformed
        try {
            controller.changeKontaktName(kontaktNameFeld.getText());
        } catch (Exception e) {
            //  Handle exception
        }
    }//GEN-LAST:event_kontaktNameFeldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kontakte(new KontaktController()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton angebotZuweisen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kontaktBLZ;
    private javax.swing.JTextField kontaktBLZFeld;
    private javax.swing.JLabel kontaktBank;
    private javax.swing.JTextField kontaktBankFeld;
    private javax.swing.JLabel kontaktEmail;
    private javax.swing.JTextField kontaktEmailFeld;
    private javax.swing.JButton kontaktHinzufuegen;
    private javax.swing.JLabel kontaktInfoLabel;
    private javax.swing.JLabel kontaktKonto;
    private javax.swing.JTextField kontaktKontoFeld;
    private javax.swing.JLabel kontaktListeLabel;
    private javax.swing.JLabel kontaktName;
    private javax.swing.JTextField kontaktNameFeld;
    private javax.swing.JLabel kontaktTel;
    private javax.swing.JTextField kontaktTelFeld;
    private javax.swing.JList kundenListe;
    // End of variables declaration//GEN-END:variables

    @Override
    public void modelPropertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(KontaktController.KONTAKT_NAME_PROPERTY)) {
            kontaktNameFeld.setText((String) evt.getNewValue());
        }
    }
}
