/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MitarbeiterView.java
 *
 * Created on 06.06.2011, 20:23:27
 */
package view;

import controller.Binder;
import controller.BinderProperty;
import controller.MitarbeiterController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import model.Mitarbeiter;
import model.dal.DALException;
import model.dal.DALFactory;
import model.dal.IDAL;
import utils.log.Logger;

/**
 *
 * @author Goran-Goggy
 */
public class MitarbeiterView extends AbstractViewPanel {

    private MitarbeiterController controller;
    private IDAL db = DALFactory.getDAL();

    /** Creates new form MitarbeiterView */
    public MitarbeiterView(MitarbeiterController controller) {
        initComponents();
        this.controller = controller;
        initialize();
    }

    private void initialize() {
        Binder.bind(Mitarbeiter.class, mitarbeiterListe);

        Binder.bind(mitarbeiterListe, mitarbeiterVornameFeld);
        Binder.bind(mitarbeiterListe, mitarbeiterNachnameFeld);
        Binder.bind(mitarbeiterListe, mitarbeiterGeburtsdatumFeld);
        Binder.bind(mitarbeiterListe, mitarbeiterStundensatzFeld);
        Binder.bind(mitarbeiterListe, mitarbeiterProjektListe);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mitarbeiterListeLabel = new javax.swing.JLabel();
        mitarbeiterVornameLabel = new javax.swing.JLabel();
        mitarbeiterAendern = new javax.swing.JButton();
        mitarbeiterGeburtsdatumFeld = new com.toedter.calendar.JDateChooser();
        mitarbeiterLoeschen = new javax.swing.JButton();
        mitarbeiterNachnameFeld = new javax.swing.JTextField();
        mitarbeiterStundensatzFeld = new javax.swing.JTextField();
        mitarbeiterGeburtsDatumLabel = new javax.swing.JLabel();
        mitarbeiterProjektZuweisen = new javax.swing.JButton();
        mitarbeiterInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mitarbeiterListe = new javax.swing.JList();
        mitarbeiterStundenSatzLabel = new javax.swing.JLabel();
        mitarbeiterNachnameLabel = new javax.swing.JLabel();
        mitarbeiterVornameFeld = new javax.swing.JTextField();
        mitarbeiterHinzufuegen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mitarbeiterProjektListe = new javax.swing.JList();
        mitarbeiterListeLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mitarbeiterListeLabel.setFont(new java.awt.Font("Arial", 1, 14));
        mitarbeiterListeLabel.setText("Mitarbeiterliste");
        add(mitarbeiterListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        mitarbeiterVornameLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterVornameLabel.setText("Vorname");
        add(mitarbeiterVornameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        mitarbeiterAendern.setText("Mitarbeiterdaten ändern");
        mitarbeiterAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterAendernActionPerformed(evt);
            }
        });
        add(mitarbeiterAendern, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, -1));

        mitarbeiterGeburtsdatumFeld.setName("Geburtsdatum"); // NOI18N
        add(mitarbeiterGeburtsdatumFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 130, -1));

        mitarbeiterLoeschen.setText("Mitarbeiter löschen");
        mitarbeiterLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterLoeschenActionPerformed(evt);
            }
        });
        add(mitarbeiterLoeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 230, -1));

        mitarbeiterNachnameFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterNachnameFeld.setName("Nachname"); // NOI18N
        add(mitarbeiterNachnameFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 150, -1));

        mitarbeiterStundensatzFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterStundensatzFeld.setName("Stundensatz"); // NOI18N
        add(mitarbeiterStundensatzFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 110, -1));

        mitarbeiterGeburtsDatumLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterGeburtsDatumLabel.setText("Geburtsdatum");
        add(mitarbeiterGeburtsDatumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        mitarbeiterProjektZuweisen.setText("Projekt zuweisen");
        mitarbeiterProjektZuweisen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterProjektZuweisenActionPerformed(evt);
            }
        });
        add(mitarbeiterProjektZuweisen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        mitarbeiterInfoLabel.setFont(new java.awt.Font("Arial", 1, 14));
        mitarbeiterInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mitarbeiterInfoLabel.setText("Mitarbeiterinformation");
        mitarbeiterInfoLabel.setAlignmentX(0.5F);
        add(mitarbeiterInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        mitarbeiterListe.setFont(new java.awt.Font("Tahoma", 2, 12));
        mitarbeiterListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mitarbeiterListe.setName("MitarbeiterListe"); // NOI18N
        mitarbeiterListe.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mitarbeiterListeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mitarbeiterListe);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 190));

        mitarbeiterStundenSatzLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterStundenSatzLabel.setText("Stundensatz (€)");
        add(mitarbeiterStundenSatzLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        mitarbeiterNachnameLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterNachnameLabel.setText("Nachname");
        add(mitarbeiterNachnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        mitarbeiterVornameFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterVornameFeld.setName("Vorname"); // NOI18N
        add(mitarbeiterVornameFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 150, -1));

        mitarbeiterHinzufuegen.setText("Mitarbeiter hinzufügen");
        mitarbeiterHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterHinzufuegenActionPerformed(evt);
            }
        });
        add(mitarbeiterHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 230, -1));

        mitarbeiterProjektListe.setFont(new java.awt.Font("Tahoma", 2, 12));
        mitarbeiterProjektListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mitarbeiterProjektListe.setName("ProjektFromMitarbeiter"); // NOI18N
        mitarbeiterProjektListe.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mitarbeiterProjektListeValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(mitarbeiterProjektListe);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 200, 190));

        mitarbeiterListeLabel1.setFont(new java.awt.Font("Arial", 0, 14));
        mitarbeiterListeLabel1.setText("Projekte vom Mitarbeiter");
        add(mitarbeiterListeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mitarbeiterListeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mitarbeiterListeValueChanged
}//GEN-LAST:event_mitarbeiterListeValueChanged

    private void mitarbeiterHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterHinzufuegenActionPerformed
        DefaultListModel model = (DefaultListModel) mitarbeiterListe.getModel();
        // solange ein nicht gespeicherter Kontakt, kein neuer Kontakt
        if(model.getSize() > 0 && ((Mitarbeiter)model.getElementAt(model.getSize()-1)).getId() == 0)
            return;
        Mitarbeiter m = new Mitarbeiter();
        m.setId(0);
        model.addElement(m);
        mitarbeiterListe.setSelectedIndex(model.getSize()-1);
        this.resetFields();
}//GEN-LAST:event_mitarbeiterHinzufuegenActionPerformed

    private void mitarbeiterLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterLoeschenActionPerformed
        Mitarbeiter m = (Mitarbeiter) this.mitarbeiterListe.getSelectedValue();
        try {
            if (!(mitarbeiterListe.isSelectionEmpty())) {
                db.deleteMitarbeiter(m);
            }
        } catch (DALException ex) {
            Logger.log(Level.SEVERE, KontakteView.class, ex);
        }
}//GEN-LAST:event_mitarbeiterLoeschenActionPerformed

    private void mitarbeiterAendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterAendernActionPerformed
        if (this.mitarbeiterListe.isSelectionEmpty()) {
            return;
        }

        ArrayList<String> errorList;
        errorList = Binder.save(Mitarbeiter.class, createBinderPropertiesFromFields());
        showErrors(errorList);
    }//GEN-LAST:event_mitarbeiterAendernActionPerformed

    private ArrayList<BinderProperty> createBinderPropertiesFromFields() {
        ArrayList list = new ArrayList<BinderProperty>();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        list.add(new BinderProperty(mitarbeiterVornameFeld.getName(), mitarbeiterVornameFeld.getText(), String.class));
        list.add(new BinderProperty(mitarbeiterNachnameFeld.getName(), mitarbeiterNachnameFeld.getText(), String.class));
        list.add(new BinderProperty(mitarbeiterStundensatzFeld.getName(), mitarbeiterStundensatzFeld.getText(), Double.class));
        list.add(new BinderProperty(mitarbeiterGeburtsdatumFeld.getName(), mitarbeiterGeburtsdatumFeld.getDate() != null ? sdf.format(mitarbeiterGeburtsdatumFeld.getDate()) : "", Date.class));
        Mitarbeiter m = (Mitarbeiter) mitarbeiterListe.getSelectedValue();
        if (m != null) {
            list.add(new BinderProperty("Id", m.getId().toString(), Integer.class));
        } else {
            list.add(new BinderProperty("Id", "0", Integer.class));
        }
        return list;
    }

    private void mitarbeiterProjektZuweisenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterProjektZuweisenActionPerformed
}//GEN-LAST:event_mitarbeiterProjektZuweisenActionPerformed

    private void mitarbeiterProjektListeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mitarbeiterProjektListeValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mitarbeiterProjektListeValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mitarbeiterAendern;
    private javax.swing.JLabel mitarbeiterGeburtsDatumLabel;
    private com.toedter.calendar.JDateChooser mitarbeiterGeburtsdatumFeld;
    private javax.swing.JButton mitarbeiterHinzufuegen;
    private javax.swing.JLabel mitarbeiterInfoLabel;
    private javax.swing.JList mitarbeiterListe;
    private javax.swing.JLabel mitarbeiterListeLabel;
    private javax.swing.JLabel mitarbeiterListeLabel1;
    private javax.swing.JButton mitarbeiterLoeschen;
    private javax.swing.JTextField mitarbeiterNachnameFeld;
    private javax.swing.JLabel mitarbeiterNachnameLabel;
    private javax.swing.JList mitarbeiterProjektListe;
    private javax.swing.JButton mitarbeiterProjektZuweisen;
    private javax.swing.JLabel mitarbeiterStundenSatzLabel;
    private javax.swing.JTextField mitarbeiterStundensatzFeld;
    private javax.swing.JTextField mitarbeiterVornameFeld;
    private javax.swing.JLabel mitarbeiterVornameLabel;
    // End of variables declaration//GEN-END:variables
}
