/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MitarbeiterView.java
 *
 * Created on 06.06.2011, 20:23:27
 */
package view;

import controller.Binder;
import controller.BinderProperty;
import controller.MitarbeiterController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import model.Mitarbeiter;
import model.dal.DALException;
import model.dal.DALFactory;
import model.dal.IDAL;
import utils.log.Logger;

/**
 *
 * @author Goran-Goggy
 */
public class MitarbeiterView extends AbstractViewPanel {

    private MitarbeiterController controller;
    private IDAL db = DALFactory.getDAL();

    /** Creates new form MitarbeiterView */
    public MitarbeiterView(MitarbeiterController controller) {
        initComponents();
        this.controller = controller;
        initialize();
    }

    private void initialize() {
        Binder.bind(Mitarbeiter.class, mitarbeiterListe);

        Binder.bind(mitarbeiterListe, mitarbeiterVornameFeld);
        Binder.bind(mitarbeiterListe, mitarbeiterNachnameFeld);
        Binder.bind(mitarbeiterListe, mitarbeiterGeburtsdatumFeld);
        Binder.bind(mitarbeiterListe, mitarbeiterStundensatzFeld);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mitarbeiterListeLabel = new javax.swing.JLabel();
        mitarbeiterInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mitarbeiterListe = new javax.swing.JList();
        mitarbeiterKontoNrLabel = new javax.swing.JLabel();
        mitarbeiterVornameLabel = new javax.swing.JLabel();
        mitarbeiterGeburtsDatumLabel = new javax.swing.JLabel();
        mitarbeiterStundenSatzLabel = new javax.swing.JLabel();
        mitarbeiterStundensatzFeld = new javax.swing.JTextField();
        mitarbeiterHinzufuegen = new javax.swing.JButton();
        mitarbeiterLoeschen = new javax.swing.JButton();
        mitarbeiterVornameFeld = new javax.swing.JTextField();
        mitarbeiterProjektZuweisen = new javax.swing.JButton();
        mitarbeiterNachnameLabel = new javax.swing.JLabel();
        mitarbeiterNachnameFeld = new javax.swing.JTextField();
        mitarbeiterStrasseLabel = new javax.swing.JLabel();
        mitarbeiterStrasseFeld = new javax.swing.JTextField();
        mitarbeiterHausNrLabel = new javax.swing.JLabel();
        mitarbeiterPlzLabel = new javax.swing.JLabel();
        mitarbeiterOrtLabel = new javax.swing.JLabel();
        mitarbeiterOrtFeld = new javax.swing.JTextField();
        mitarbeiterAendern = new javax.swing.JButton();
        mitarbeiterPlzFeld = new javax.swing.JTextField();
        mitarbeiterHausNrFeld = new javax.swing.JTextField();
        mitarbeiterKontoNrFeld = new javax.swing.JTextField();
        mitarbeiterGeburtsdatumFeld = new com.toedter.calendar.JDateChooser();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mitarbeiterListeLabel.setFont(new java.awt.Font("Arial", 1, 14));
        mitarbeiterListeLabel.setText("Mitarbeiterliste");
        jPanel1.add(mitarbeiterListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        mitarbeiterInfoLabel.setFont(new java.awt.Font("Arial", 1, 14));
        mitarbeiterInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mitarbeiterInfoLabel.setText("Mitarbeiterinformation");
        mitarbeiterInfoLabel.setAlignmentX(0.5F);
        jPanel1.add(mitarbeiterInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        mitarbeiterListe.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        mitarbeiterListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mitarbeiterListe.setName("MitarbeiterListe"); // NOI18N
        mitarbeiterListe.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mitarbeiterListeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mitarbeiterListe);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 190));

        mitarbeiterKontoNrLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterKontoNrLabel.setText("Konto-Nr.");
        jPanel1.add(mitarbeiterKontoNrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        mitarbeiterVornameLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterVornameLabel.setText("Vorname");
        jPanel1.add(mitarbeiterVornameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        mitarbeiterGeburtsDatumLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterGeburtsDatumLabel.setText("Geburtsdatum");
        jPanel1.add(mitarbeiterGeburtsDatumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        mitarbeiterStundenSatzLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterStundenSatzLabel.setText("Stundensatz (€)");
        jPanel1.add(mitarbeiterStundenSatzLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        mitarbeiterStundensatzFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterStundensatzFeld.setName("Stundensatz"); // NOI18N
        jPanel1.add(mitarbeiterStundensatzFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 110, -1));

        mitarbeiterHinzufuegen.setText("Mitarbeiter hinzufügen");
        mitarbeiterHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterHinzufuegenActionPerformed(evt);
            }
        });
        jPanel1.add(mitarbeiterHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, -1));

        mitarbeiterLoeschen.setText("Mitarbeiter löschen");
        mitarbeiterLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterLoeschenActionPerformed(evt);
            }
        });
        jPanel1.add(mitarbeiterLoeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 230, -1));

        mitarbeiterVornameFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterVornameFeld.setName("Vorname"); // NOI18N
        jPanel1.add(mitarbeiterVornameFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 150, -1));

        mitarbeiterProjektZuweisen.setText("Projekt zuweisen");
        mitarbeiterProjektZuweisen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterProjektZuweisenActionPerformed(evt);
            }
        });
        jPanel1.add(mitarbeiterProjektZuweisen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        mitarbeiterNachnameLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterNachnameLabel.setText("Nachname");
        jPanel1.add(mitarbeiterNachnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        mitarbeiterNachnameFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterNachnameFeld.setName("Nachname"); // NOI18N
        jPanel1.add(mitarbeiterNachnameFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 150, -1));

        mitarbeiterStrasseLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterStrasseLabel.setText("Straße");
        jPanel1.add(mitarbeiterStrasseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        mitarbeiterStrasseFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterStrasseFeld.setName("Strasse"); // NOI18N
        jPanel1.add(mitarbeiterStrasseFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 150, -1));

        mitarbeiterHausNrLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterHausNrLabel.setText("Haus-Nr.");
        jPanel1.add(mitarbeiterHausNrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        mitarbeiterPlzLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterPlzLabel.setText("PLZ");
        jPanel1.add(mitarbeiterPlzLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));

        mitarbeiterOrtLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        mitarbeiterOrtLabel.setText("Ort");
        jPanel1.add(mitarbeiterOrtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        mitarbeiterOrtFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterOrtFeld.setName("Ort"); // NOI18N
        jPanel1.add(mitarbeiterOrtFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, -1));

        mitarbeiterAendern.setText("Mitarbeiterdaten ändern");
        mitarbeiterAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitarbeiterAendernActionPerformed(evt);
            }
        });
        jPanel1.add(mitarbeiterAendern, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 230, -1));

        mitarbeiterPlzFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterPlzFeld.setName("Plz"); // NOI18N
        jPanel1.add(mitarbeiterPlzFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 150, -1));

        mitarbeiterHausNrFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterHausNrFeld.setName("Hausnr"); // NOI18N
        jPanel1.add(mitarbeiterHausNrFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 150, -1));

        mitarbeiterKontoNrFeld.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mitarbeiterKontoNrFeld.setName("Konto"); // NOI18N
        jPanel1.add(mitarbeiterKontoNrFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 150, -1));

        mitarbeiterGeburtsdatumFeld.setName("Geburtsdatum"); // NOI18N
        jPanel1.add(mitarbeiterGeburtsdatumFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mitarbeiterListeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mitarbeiterListeValueChanged
}//GEN-LAST:event_mitarbeiterListeValueChanged

    private void mitarbeiterHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterHinzufuegenActionPerformed
        DefaultListModel model = (DefaultListModel) mitarbeiterListe.getModel();
        // solange ein nicht gespeicherter Kontakt, kein neuer Kontakt
        if(model.getSize() > 0 && ((Mitarbeiter)model.getElementAt(model.getSize()-1)).getId() == 0)
            return;
        Mitarbeiter m = new Mitarbeiter();
        m.setId(0);
        model.addElement(m);
        mitarbeiterListe.setSelectedIndex(model.getSize()-1);
        this.resetFields();
}//GEN-LAST:event_mitarbeiterHinzufuegenActionPerformed

    private void mitarbeiterLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterLoeschenActionPerformed
        Mitarbeiter m = (Mitarbeiter) this.mitarbeiterListe.getSelectedValue();
        try {
            if (!(mitarbeiterListe.isSelectionEmpty())) {
                db.deleteMitarbeiter(m);
            }
        } catch (DALException ex) {
            Logger.log(Level.SEVERE, KontakteView.class, ex);
        }
}//GEN-LAST:event_mitarbeiterLoeschenActionPerformed

    private void mitarbeiterAendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterAendernActionPerformed
        if (this.mitarbeiterListe.isSelectionEmpty()) {
            return;
        }

        ArrayList<String> errorList;
        errorList = Binder.save(Mitarbeiter.class, createBinderPropertiesFromFields());
        showErrors(errorList);
    }//GEN-LAST:event_mitarbeiterAendernActionPerformed

    private ArrayList<BinderProperty> createBinderPropertiesFromFields() {
        ArrayList list = new ArrayList<BinderProperty>();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");

        list.add(new BinderProperty(mitarbeiterVornameFeld.getName(), mitarbeiterVornameFeld.getText(), String.class));
        list.add(new BinderProperty(mitarbeiterNachnameFeld.getName(), mitarbeiterNachnameFeld.getText(), String.class));
        list.add(new BinderProperty(mitarbeiterStundensatzFeld.getName(), mitarbeiterStundensatzFeld.getText(), Double.class));
        list.add(new BinderProperty(mitarbeiterGeburtsdatumFeld.getName(), mitarbeiterGeburtsdatumFeld.getDate() != null ? sdf.format(mitarbeiterGeburtsdatumFeld.getDate()) : "", Date.class));
        Mitarbeiter m = (Mitarbeiter) mitarbeiterListe.getSelectedValue();
        if (m != null) {
            list.add(new BinderProperty("Id", m.getId().toString(), Integer.class));
        } else {
            list.add(new BinderProperty("Id", "0", Integer.class));
        }
        return list;
    }

    private void mitarbeiterProjektZuweisenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitarbeiterProjektZuweisenActionPerformed
}//GEN-LAST:event_mitarbeiterProjektZuweisenActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mitarbeiterAendern;
    private javax.swing.JLabel mitarbeiterGeburtsDatumLabel;
    private com.toedter.calendar.JDateChooser mitarbeiterGeburtsdatumFeld;
    private javax.swing.JTextField mitarbeiterHausNrFeld;
    private javax.swing.JLabel mitarbeiterHausNrLabel;
    private javax.swing.JButton mitarbeiterHinzufuegen;
    private javax.swing.JLabel mitarbeiterInfoLabel;
    private javax.swing.JTextField mitarbeiterKontoNrFeld;
    private javax.swing.JLabel mitarbeiterKontoNrLabel;
    private javax.swing.JList mitarbeiterListe;
    private javax.swing.JLabel mitarbeiterListeLabel;
    private javax.swing.JButton mitarbeiterLoeschen;
    private javax.swing.JTextField mitarbeiterNachnameFeld;
    private javax.swing.JLabel mitarbeiterNachnameLabel;
    private javax.swing.JTextField mitarbeiterOrtFeld;
    private javax.swing.JLabel mitarbeiterOrtLabel;
    private javax.swing.JTextField mitarbeiterPlzFeld;
    private javax.swing.JLabel mitarbeiterPlzLabel;
    private javax.swing.JButton mitarbeiterProjektZuweisen;
    private javax.swing.JTextField mitarbeiterStrasseFeld;
    private javax.swing.JLabel mitarbeiterStrasseLabel;
    private javax.swing.JLabel mitarbeiterStundenSatzLabel;
    private javax.swing.JTextField mitarbeiterStundensatzFeld;
    private javax.swing.JTextField mitarbeiterVornameFeld;
    private javax.swing.JLabel mitarbeiterVornameLabel;
    // End of variables declaration//GEN-END:variables
}
