/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Rechnungsueberblick.java
 *
 * Created on 08.06.2011, 19:46:35
 */
package view;

import javax.swing.JPanel;

/**
 *
 * @author Goran-Goggy
 */
public class Rechnungsueberblick extends javax.swing.JPanel {
    /** Creates new form Rechnungsueberblick */
    public Rechnungsueberblick() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechnungsUeberblickPane = new javax.swing.JTabbedPane();

        rechnungsUeberblickPane.setName("rechnungsUeberblickPane"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rechnungsUeberblickPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rechnungsUeberblickPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane rechnungsUeberblickPane;
    // End of variables declaration//GEN-END:variables
    public void addTabPanel(JPanel panel, String title) {
        this.rechnungsUeberblickPane.add(panel, title);
    }
}
