/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Rechnungszeilen.java
 *
 * Created on 09.06.2011, 03:56:13
 */
package view;

import controller.RechnungszeilenController;

/**
 *
 * @author Goran-Goggy
 */
public class Rechnungszeilen extends javax.swing.JPanel {
private RechnungszeilenController controller;
    /** Creates new form Rechnungszeilen */
    public Rechnungszeilen(RechnungszeilenController controller) {
        this.controller = controller;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BankOffeneRechnungenListeLabel = new javax.swing.JLabel();
        rechnungszeileDatenLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rechnungszeileZeilenListe = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        rechnungszeileRechnungenListe = new javax.swing.JList();
        rechnungszeileTextLabel = new javax.swing.JLabel();
        rechnungszeilePreisFeld = new javax.swing.JTextField();
        rechnungszeileAngebotLabel = new javax.swing.JLabel();
        rechnungszeileAngebotCheckbox = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        rechnungszeileTextFeld = new javax.swing.JTextArea();
        rechnungszeilePreisLabel = new javax.swing.JLabel();
        rechnungszeileRechnungenLabel = new javax.swing.JLabel();
        rechnungszeileZeilenLabel = new javax.swing.JLabel();
        rechnungszeileZeilenLoeschen = new javax.swing.JButton();
        rechnungszeileZeilenHinzufuegen = new javax.swing.JButton();
        rechnungszeileZeilenZuweisen = new javax.swing.JButton();
        rechnungszeileZeilenAendern = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BankOffeneRechnungenListeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(BankOffeneRechnungenListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        rechnungszeileDatenLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rechnungszeileDatenLabel.setText("Rechnungszeilendaten");
        jPanel1.add(rechnungszeileDatenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        rechnungszeileZeilenListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(rechnungszeileZeilenListe);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 180, 180));

        rechnungszeileRechnungenListe.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        rechnungszeileRechnungenListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        rechnungszeileRechnungenListe.setName("ProjektListe"); // NOI18N
        jScrollPane2.setViewportView(rechnungszeileRechnungenListe);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 160, 180));

        rechnungszeileTextLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        rechnungszeileTextLabel.setText("Text");
        jPanel1.add(rechnungszeileTextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        rechnungszeilePreisFeld.setEnabled(false);
        rechnungszeilePreisFeld.setName("Name"); // NOI18N
        rechnungszeilePreisFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechnungszeilePreisFeldActionPerformed(evt);
            }
        });
        jPanel1.add(rechnungszeilePreisFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, -1));

        rechnungszeileAngebotLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        rechnungszeileAngebotLabel.setText("Angebot");
        jPanel1.add(rechnungszeileAngebotLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        rechnungszeileAngebotCheckbox.setEnabled(false);
        rechnungszeileAngebotCheckbox.setName("Angebot"); // NOI18N
        jPanel1.add(rechnungszeileAngebotCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 180, -1));

        rechnungszeileTextFeld.setColumns(20);
        rechnungszeileTextFeld.setRows(5);
        jScrollPane3.setViewportView(rechnungszeileTextFeld);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 126, 550, 90));

        rechnungszeilePreisLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        rechnungszeilePreisLabel.setText("Preis");
        jPanel1.add(rechnungszeilePreisLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        rechnungszeileRechnungenLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rechnungszeileRechnungenLabel.setText("Rechnungsliste");
        jPanel1.add(rechnungszeileRechnungenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        rechnungszeileZeilenLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rechnungszeileZeilenLabel.setText("Rechnungszeilen");
        jPanel1.add(rechnungszeileZeilenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        rechnungszeileZeilenLoeschen.setText("Rechnungszeile löschen");
        rechnungszeileZeilenLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechnungszeileZeilenLoeschenActionPerformed(evt);
            }
        });
        jPanel1.add(rechnungszeileZeilenLoeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 170, -1));

        rechnungszeileZeilenHinzufuegen.setText("Rechnungszeile erstellen");
        rechnungszeileZeilenHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechnungszeileZeilenHinzufuegenActionPerformed(evt);
            }
        });
        jPanel1.add(rechnungszeileZeilenHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 170, -1));

        rechnungszeileZeilenZuweisen.setText("Rechnungszeile zuweisen");
        rechnungszeileZeilenZuweisen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechnungszeileZeilenZuweisenActionPerformed(evt);
            }
        });
        jPanel1.add(rechnungszeileZeilenZuweisen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 180, -1));

        rechnungszeileZeilenAendern.setText("Rechnungszeile sichern");
        rechnungszeileZeilenAendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechnungszeileZeilenAendernActionPerformed(evt);
            }
        });
        jPanel1.add(rechnungszeileZeilenAendern, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 170, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1000, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void rechnungszeilePreisFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechnungszeilePreisFeldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_rechnungszeilePreisFeldActionPerformed

    private void rechnungszeileZeilenLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechnungszeileZeilenLoeschenActionPerformed

}//GEN-LAST:event_rechnungszeileZeilenLoeschenActionPerformed

    private void rechnungszeileZeilenHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechnungszeileZeilenHinzufuegenActionPerformed

}//GEN-LAST:event_rechnungszeileZeilenHinzufuegenActionPerformed

    private void rechnungszeileZeilenZuweisenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechnungszeileZeilenZuweisenActionPerformed
        
}//GEN-LAST:event_rechnungszeileZeilenZuweisenActionPerformed

    private void rechnungszeileZeilenAendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechnungszeileZeilenAendernActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechnungszeileZeilenAendernActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BankOffeneRechnungenListeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox rechnungszeileAngebotCheckbox;
    private javax.swing.JLabel rechnungszeileAngebotLabel;
    private javax.swing.JLabel rechnungszeileDatenLabel;
    private javax.swing.JTextField rechnungszeilePreisFeld;
    private javax.swing.JLabel rechnungszeilePreisLabel;
    private javax.swing.JLabel rechnungszeileRechnungenLabel;
    private javax.swing.JList rechnungszeileRechnungenListe;
    private javax.swing.JTextArea rechnungszeileTextFeld;
    private javax.swing.JLabel rechnungszeileTextLabel;
    private javax.swing.JButton rechnungszeileZeilenAendern;
    private javax.swing.JButton rechnungszeileZeilenHinzufuegen;
    private javax.swing.JLabel rechnungszeileZeilenLabel;
    private javax.swing.JList rechnungszeileZeilenListe;
    private javax.swing.JButton rechnungszeileZeilenLoeschen;
    private javax.swing.JButton rechnungszeileZeilenZuweisen;
    // End of variables declaration//GEN-END:variables
}
