/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatistikView.java
 *
 * Created on 09.05.2011, 17:49:11
 */
package view;

import controller.StatistikController;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import model.dal.DALFactory;
import model.dal.IDAL;
import utils.log.Logger;
import utils.documents.StatistikPDF;
import view.dialog.AusgangsrechnungForm;
import view.dialog.EingangsrechnungForm;
import view.dialog.JahresUeberblickForm;

/**
 *
 * @author Goran-Goggy
 */
public class StatistikView extends javax.swing.JPanel {

    private StatistikController controller;
    private IDAL db = DALFactory.getDAL();

    /** Creates new form StatistikView */
    public StatistikView(StatistikController controller) {
        initComponents();
        this.controller = controller;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kontaktListeLabel = new javax.swing.JLabel();
        kontaktInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statistikEingang = new javax.swing.JList();
        statistikAusgangHinzufuegen = new javax.swing.JButton();
        statistikEingangHinzufuegen = new javax.swing.JButton();
        statistikJahr = new javax.swing.JButton();
        statistikPDF = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        statistikAusgang = new javax.swing.JList();
        kontaktListeLabel1 = new javax.swing.JLabel();
        statistikMonat = new javax.swing.JComboBox();
        kontaktListeLabel2 = new javax.swing.JLabel();
        statistikErloes = new javax.swing.JTextField();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kontaktListeLabel.setFont(new java.awt.Font("Arial", 1, 14));
        kontaktListeLabel.setText("Erlösstand (€)");
        add(kontaktListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 20));

        kontaktInfoLabel.setFont(new java.awt.Font("Arial", 1, 14));
        kontaktInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kontaktInfoLabel.setText("Eingangsrechnung");
        kontaktInfoLabel.setAlignmentX(0.5F);
        add(kontaktInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        statistikEingang.setFont(new java.awt.Font("Tahoma", 2, 12));
        statistikEingang.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Wien Energie", "FH Technikum-Wien" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        statistikEingang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        statistikEingang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statistikEingangMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(statistikEingang);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 480, 140));

        statistikAusgangHinzufuegen.setText("Ausgangsrechnung hinzufügen");
        statistikAusgangHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistikAusgangHinzufuegenActionPerformed(evt);
            }
        });
        add(statistikAusgangHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 230, -1));

        statistikEingangHinzufuegen.setText("Eingangsrechnung hinzufügen");
        add(statistikEingangHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 230, -1));

        statistikJahr.setText("Jahresüberblick anzeigen");
        statistikJahr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistikJahrActionPerformed(evt);
            }
        });
        add(statistikJahr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        statistikPDF.setText("PDF erstellen");
        statistikPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistikPDFActionPerformed(evt);
            }
        });
        add(statistikPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 230, -1));

        statistikAusgang.setFont(new java.awt.Font("Tahoma", 2, 12));
        statistikAusgang.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Wien Energie", "FH Technikum-Wien", "Wien Energie", "FH Technikum-Wien" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        statistikAusgang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        statistikAusgang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                statistikAusgangMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(statistikAusgang);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 470, 140));

        kontaktListeLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        kontaktListeLabel1.setText("Ausgangsrechnung");
        add(kontaktListeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        statistikMonat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jänner", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));
        add(statistikMonat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, 20));

        kontaktListeLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        kontaktListeLabel2.setText("Statistik des Monats");
        add(kontaktListeLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        statistikErloes.setEditable(false);
        statistikErloes.setText("50000");
        add(statistikErloes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 150, -1));
        add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void statistikAusgangHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistikAusgangHinzufuegenActionPerformed
        //KontaktAddForm af = new KontaktAddForm(null, true);
        //af.setVisible(true);
}//GEN-LAST:event_statistikAusgangHinzufuegenActionPerformed

    private void statistikPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistikPDFActionPerformed
        //http://www.easy-coding.de/externe-datei-pdf-oeffnen-mit-java-t2662.html


        ArrayList<String> eingang = new ArrayList<String>();
        for (int i = 0; i < statistikEingang.getModel().getSize(); i++) {
            eingang.add(statistikEingang.getModel().getElementAt(i).toString());
        }

        ArrayList<String> ausgang = new ArrayList<String>();
        for (int i = 0; i < statistikAusgang.getModel().getSize(); i++) {
            ausgang.add(statistikAusgang.getModel().getElementAt(i).toString());
        }

        String monat = statistikMonat.getSelectedItem().toString();
        String erloes = statistikErloes.getText();
        StatistikPDF statistik = new StatistikPDF(monat, ausgang, eingang, erloes);
        statistik.createPDF("StatistikPDF.pdf");

        Desktop d = Desktop.getDesktop();
        try {
            d.open(new File("docs\\StatistikPDF.pdf"));
        } catch (IOException ex) {
            Logger.log(Level.SEVERE, StatistikView.class, ex);
        }
}//GEN-LAST:event_statistikPDFActionPerformed

    private void statistikEingangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistikEingangMousePressed
        // TODO add your handling code here:
        EingangsrechnungForm eRF = new EingangsrechnungForm(null, true);
        eRF.setVisible(true);
    }//GEN-LAST:event_statistikEingangMousePressed

    private void statistikAusgangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statistikAusgangMousePressed
        // TODO add your handling code here:
        AusgangsrechnungForm aRF = new AusgangsrechnungForm(null, true);
        aRF.setVisible(true);
    }//GEN-LAST:event_statistikAusgangMousePressed

    private void statistikJahrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistikJahrActionPerformed
        // TODO add your handling code here:
        JahresUeberblickForm jUF = new JahresUeberblickForm(null, true);
        jUF.setVisible(true);
    }//GEN-LAST:event_statistikJahrActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel kontaktInfoLabel;
    private javax.swing.JLabel kontaktListeLabel;
    private javax.swing.JLabel kontaktListeLabel1;
    private javax.swing.JLabel kontaktListeLabel2;
    private javax.swing.JList statistikAusgang;
    private javax.swing.JButton statistikAusgangHinzufuegen;
    private javax.swing.JList statistikEingang;
    private javax.swing.JButton statistikEingangHinzufuegen;
    private javax.swing.JTextField statistikErloes;
    private javax.swing.JButton statistikJahr;
    private javax.swing.JComboBox statistikMonat;
    private javax.swing.JButton statistikPDF;
    // End of variables declaration//GEN-END:variables
}
