/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ZeitErfassungView.java
 *
 * Created on 06.06.2011, 15:31:47
 */
package view;

import java.io.File;
import javax.swing.Action;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import utils.csv.SaveFileAction;
import utils.csv.OpenFileAction;
import utils.csv.CSVFilter;

/**
 *
 * @author Goran-Goggy
 */
public class ZeitErfassungView extends javax.swing.JPanel {
    private FileSystemView fsv = FileSystemView.getFileSystemView();
    private JFileChooser fc = new JFileChooser(fsv.getRoots()[0]);
// Create the actions
    private Action openAction = new OpenFileAction(this, fc);
    private Action saveAction = new SaveFileAction(this, fc);
    private File f;

    /** Creates new form ProjektView */
    public ZeitErfassungView() {
        initComponents();
        fc.addChoosableFileFilter(new CSVFilter());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logListeLabel = new javax.swing.JLabel();
        logInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logListe = new javax.swing.JList();
        logMitarbeiterIDLabel = new javax.swing.JLabel();
        projektImplementierungVonLabel = new javax.swing.JLabel();
        projektExport = new javax.swing.JButton(saveAction);
        logMitarbeiterIDFeld = new javax.swing.JTextField();
        projektImport = new javax.swing.JButton(openAction);
        logProjektIdLabell = new javax.swing.JLabel();
        logProjektIdFeld = new javax.swing.JTextField();
        logHinzufuegen = new javax.swing.JButton();
        logLoeschen = new javax.swing.JButton();
        logPdfErstellen = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        logMitarbeiterStundenLabel = new javax.swing.JLabel();
        logMitarbeiterIDFeld1 = new javax.swing.JTextField();
        logTaetigkeitLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logTaetigkeitFeld = new javax.swing.JTextArea();
        projektAendern1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logListeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logListeLabel.setText("Logeinträge");
        jPanel1.add(logListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logInfoLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logInfoLabel.setText("Logeintrag");
        logInfoLabel.setAlignmentX(0.5F);
        jPanel1.add(logInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        logListe.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        logListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Projekt 1  |  Auftrag 1", "Projekt 2", "Projekt 3", "Projekt 4", "Projekt 5", "Projekt 6", "Projekt 7" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        logListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(logListe);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 190));

        logMitarbeiterIDLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        logMitarbeiterIDLabel.setText("Mitarbeiter-ID");
        jPanel1.add(logMitarbeiterIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        projektImplementierungVonLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        projektImplementierungVonLabel.setText("Eintrag am");
        jPanel1.add(projektImplementierungVonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        projektExport.setText("Datensätze exportieren");
        jPanel1.add(projektExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 230, -1));

        logMitarbeiterIDFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMitarbeiterIDFeldActionPerformed(evt);
            }
        });
        jPanel1.add(logMitarbeiterIDFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 150, -1));

        projektImport.setText("Datensätze Importieren");
        projektImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projektImportActionPerformed(evt);
            }
        });
        jPanel1.add(projektImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 230, -1));

        logProjektIdLabell.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        logProjektIdLabell.setText("Projekt-ID");
        jPanel1.add(logProjektIdLabell, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        logProjektIdFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logProjektIdFeldActionPerformed(evt);
            }
        });
        jPanel1.add(logProjektIdFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 150, -1));

        logHinzufuegen.setText("Logeintrag erstellen");
        jPanel1.add(logHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        logLoeschen.setText("Logeintrag löschen");
        jPanel1.add(logLoeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, -1));

        logPdfErstellen.setText("PDF erstellen");
        logPdfErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPdfErstellenActionPerformed(evt);
            }
        });
        jPanel1.add(logPdfErstellen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 230, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 150, -1));

        logMitarbeiterStundenLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        logMitarbeiterStundenLabel.setText("Stunden");
        jPanel1.add(logMitarbeiterStundenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        logMitarbeiterIDFeld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMitarbeiterIDFeld1ActionPerformed(evt);
            }
        });
        jPanel1.add(logMitarbeiterIDFeld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 150, -1));

        logTaetigkeitLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        logTaetigkeitLabel.setText("Tätigkeiten");
        jPanel1.add(logTaetigkeitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        logTaetigkeitFeld.setColumns(20);
        logTaetigkeitFeld.setRows(5);
        jScrollPane3.setViewportView(logTaetigkeitFeld);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 770, 90));

        projektAendern1.setText("Logeintrag ändern");
        projektAendern1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projektAendern1ActionPerformed(evt);
            }
        });
        jPanel1.add(projektAendern1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logMitarbeiterIDFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMitarbeiterIDFeldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_logMitarbeiterIDFeldActionPerformed

    private void projektImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projektImportActionPerformed
        // TODO add your handling code here:
        //fc.showOpenDialog(this);
        //System.out.println("OPEN");
        //geparst wird im CSVReader
        //openAction(fc.getSelectedFile());
}//GEN-LAST:event_projektImportActionPerformed

    private void logProjektIdFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logProjektIdFeldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_logProjektIdFeldActionPerformed

    private void logPdfErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logPdfErstellenActionPerformed
        //KontaktAddForm af = new KontaktAddForm(null, true);
        //af.setVisible(true);
}//GEN-LAST:event_logPdfErstellenActionPerformed

    private void logMitarbeiterIDFeld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMitarbeiterIDFeld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logMitarbeiterIDFeld1ActionPerformed

    private void projektAendern1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projektAendern1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projektAendern1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logHinzufuegen;
    private javax.swing.JLabel logInfoLabel;
    private javax.swing.JList logListe;
    private javax.swing.JLabel logListeLabel;
    private javax.swing.JButton logLoeschen;
    private javax.swing.JTextField logMitarbeiterIDFeld;
    private javax.swing.JTextField logMitarbeiterIDFeld1;
    private javax.swing.JLabel logMitarbeiterIDLabel;
    private javax.swing.JLabel logMitarbeiterStundenLabel;
    private javax.swing.JButton logPdfErstellen;
    private javax.swing.JTextField logProjektIdFeld;
    private javax.swing.JLabel logProjektIdLabell;
    private javax.swing.JTextArea logTaetigkeitFeld;
    private javax.swing.JLabel logTaetigkeitLabel;
    private javax.swing.JButton projektAendern1;
    private javax.swing.JButton projektExport;
    private javax.swing.JLabel projektImplementierungVonLabel;
    private javax.swing.JButton projektImport;
    // End of variables declaration//GEN-END:variables
}
