/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ZeitErfassungView.java
 *
 * Created on 06.06.2011, 15:31:47
 */
package view;

import controller.Binder;
import controller.ZeitErfassungController;
import java.io.File;
import javax.swing.Action;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import model.dal.DALFactory;
import model.dal.IDAL;
import utils.csv.SaveFileAction;
import utils.csv.OpenFileAction;
import utils.csv.CSVFilter;

/**
 *
 * @author Goran-Goggy
 */
public class ZeitErfassungView extends AbstractViewPanel {

    private ZeitErfassungController controller;
    private IDAL db = DALFactory.getDAL();
    private FileSystemView fsv = FileSystemView.getFileSystemView();
    private JFileChooser fc = new JFileChooser(fsv.getRoots()[0]);
// Create the actions
    private Action openAction = new OpenFileAction(this, fc);
    private Action saveAction = new SaveFileAction(this, fc);
    private File f;

    /** Creates new form ProjektView */
    public ZeitErfassungView(ZeitErfassungController controller) {
        this.controller = controller;
        initComponents();
        initialize();
    }
    
    private void initialize() {
        fc.addChoosableFileFilter(new CSVFilter());
        
        Binder.bind(ZeitErfassungView.class, logListe);
        
        Binder.bind(logListe, logProjektComboBox);
        Binder.bind(logListe, logMitarbeiterComboBox);
        Binder.bind(logListe, logDatumDateChooser);
        Binder.bind(logListe, logStundenFeld);
        Binder.bind(logListe, logTaetigkeitFeld);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logListeLabel = new javax.swing.JLabel();
        logInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logListe = new javax.swing.JList();
        logMitarbeiterIDLabel = new javax.swing.JLabel();
        projektImplementierungVonLabel = new javax.swing.JLabel();
        projektExport = new javax.swing.JButton(saveAction);
        projektImport = new javax.swing.JButton(openAction);
        logProjektIdLabell = new javax.swing.JLabel();
        logHinzufuegen = new javax.swing.JButton();
        logLoeschen = new javax.swing.JButton();
        logPdfErstellen = new javax.swing.JButton();
        logDatumDateChooser = new com.toedter.calendar.JDateChooser();
        logMitarbeiterStundenLabel = new javax.swing.JLabel();
        logStundenFeld = new javax.swing.JTextField();
        logTaetigkeitLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logTaetigkeitFeld = new javax.swing.JTextArea();
        projektAendern1 = new javax.swing.JButton();
        logProjektComboBox = new javax.swing.JComboBox();
        logMitarbeiterComboBox = new javax.swing.JComboBox();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logListeLabel.setFont(new java.awt.Font("Arial", 1, 14));
        logListeLabel.setText("Logeinträge");
        jPanel1.add(logListeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logInfoLabel.setFont(new java.awt.Font("Arial", 1, 14));
        logInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logInfoLabel.setText("Logeintrag");
        logInfoLabel.setAlignmentX(0.5F);
        jPanel1.add(logInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        logListe.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        logListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        logListe.setName("ArbeitsstundenListe"); // NOI18N
        jScrollPane1.setViewportView(logListe);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 190));

        logMitarbeiterIDLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        logMitarbeiterIDLabel.setText("Mitarbeiter");
        jPanel1.add(logMitarbeiterIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        projektImplementierungVonLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        projektImplementierungVonLabel.setText("Gearbeitet am");
        jPanel1.add(projektImplementierungVonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        projektExport.setText("Datensätze exportieren");
        jPanel1.add(projektExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 230, -1));

        projektImport.setText("Datensätze Importieren");
        projektImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projektImportActionPerformed(evt);
            }
        });
        jPanel1.add(projektImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 230, -1));

        logProjektIdLabell.setFont(new java.awt.Font("Tahoma", 0, 15));
        logProjektIdLabell.setText("Projekt");
        jPanel1.add(logProjektIdLabell, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        logHinzufuegen.setText("Logeintrag erstellen");
        jPanel1.add(logHinzufuegen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, -1));

        logLoeschen.setText("Logeintrag löschen");
        jPanel1.add(logLoeschen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, -1));

        logPdfErstellen.setText("PDF erstellen");
        logPdfErstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPdfErstellenActionPerformed(evt);
            }
        });
        jPanel1.add(logPdfErstellen, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 230, -1));

        logDatumDateChooser.setEnabled(false);
        logDatumDateChooser.setName("Datum"); // NOI18N
        jPanel1.add(logDatumDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 150, -1));

        logMitarbeiterStundenLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        logMitarbeiterStundenLabel.setText("Stunden");
        jPanel1.add(logMitarbeiterStundenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        logStundenFeld.setEnabled(false);
        logStundenFeld.setName("Stunden"); // NOI18N
        logStundenFeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logStundenFeldActionPerformed(evt);
            }
        });
        jPanel1.add(logStundenFeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 150, -1));

        logTaetigkeitLabel.setFont(new java.awt.Font("Tahoma", 0, 15));
        logTaetigkeitLabel.setText("Tätigkeiten");
        jPanel1.add(logTaetigkeitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        logTaetigkeitFeld.setColumns(20);
        logTaetigkeitFeld.setRows(5);
        logTaetigkeitFeld.setEnabled(false);
        logTaetigkeitFeld.setName("Taetigkeit"); // NOI18N
        jScrollPane3.setViewportView(logTaetigkeitFeld);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 770, 90));

        projektAendern1.setText("Logeintrag ändern");
        projektAendern1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projektAendern1ActionPerformed(evt);
            }
        });
        jPanel1.add(projektAendern1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 230, -1));

        logProjektComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        logProjektComboBox.setEnabled(false);
        logProjektComboBox.setName("ProjektListe"); // NOI18N
        jPanel1.add(logProjektComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 150, -1));

        logMitarbeiterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        logMitarbeiterComboBox.setEnabled(false);
        logMitarbeiterComboBox.setName("MitarbeiterListe"); // NOI18N
        jPanel1.add(logMitarbeiterComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void projektImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projektImportActionPerformed
        // TODO add your handling code here:
        //fc.showOpenDialog(this);
        //System.out.println("OPEN");
        //geparst wird im CSVReader
        //openAction(fc.getSelectedFile());
}//GEN-LAST:event_projektImportActionPerformed

    private void logPdfErstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logPdfErstellenActionPerformed
        //KontaktAddForm af = new KontaktAddForm(null, true);
        //af.setVisible(true);
}//GEN-LAST:event_logPdfErstellenActionPerformed

    private void logStundenFeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logStundenFeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logStundenFeldActionPerformed

    private void projektAendern1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projektAendern1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projektAendern1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser logDatumDateChooser;
    private javax.swing.JButton logHinzufuegen;
    private javax.swing.JLabel logInfoLabel;
    private javax.swing.JList logListe;
    private javax.swing.JLabel logListeLabel;
    private javax.swing.JButton logLoeschen;
    private javax.swing.JComboBox logMitarbeiterComboBox;
    private javax.swing.JLabel logMitarbeiterIDLabel;
    private javax.swing.JLabel logMitarbeiterStundenLabel;
    private javax.swing.JButton logPdfErstellen;
    private javax.swing.JComboBox logProjektComboBox;
    private javax.swing.JLabel logProjektIdLabell;
    private javax.swing.JTextField logStundenFeld;
    private javax.swing.JTextArea logTaetigkeitFeld;
    private javax.swing.JLabel logTaetigkeitLabel;
    private javax.swing.JButton projektAendern1;
    private javax.swing.JButton projektExport;
    private javax.swing.JLabel projektImplementierungVonLabel;
    private javax.swing.JButton projektImport;
    // End of variables declaration//GEN-END:variables
}
